# For all configuration options, see the GitHub documentation:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/pipeline/seq_retrieval/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/pipeline/seq_retrieval/tests/" # Location of package manifests
    schedule:
      interval: "weekly"
