# For all configuration options, see the GitHub documentation:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directories:
      - "**/aws_infra/"
      - "shared_aws/py_package"
    groups:
      cdk-deps-version-updates:
        applies-to: version-updates
        patterns:
          - "boto3"
          - "boto3-stubs"
          - "botocore"
          - "botocore-stubs"
          - "aws-cdk-*"
      cdk-deps-security-updates:
        applies-to: security-updates
        patterns:
          - "boto3"
          - "boto3-stubs"
          - "botocore"
          - "botocore-stubs"
          - "aws-cdk-*"
    ignore:
      # Subdependencies temporarily added to ignore list to deal with lack of subdependency support in requirements.txt files.
      # TODO: migrate to poetry 2.* once released as stable release (support for )
      #       Tracked by https://github.com/dependabot/dependabot-core/issues/8603 and https://github.com/python-poetry/poetry/issues/9136
      #       Then remove this sub-dependency ignore list
      - dependency-name: "typeguard"
      - dependency-name: "cattrs"
      - dependency-name: "s3transfer"
      # Below version upgrades are ignored because auto-updates on every PR should handle them
      # (pyproject.toml uses wildcards for minor and patch version definition)
      # Dependabot will still create PRs for security upgrades with any version.

      #Note: ignoring patch and minor version temporarily disabled to test grouping behaviour
    #   - dependency-name: "aws-cdk-*"
    #     update-types:
    #       - version-update:semver-patch
    #       - version-update:semver-minor
    #   - dependency-name: "boto3"
    #     update-types:
    #       - version-update:semver-patch
    #       - version-update:semver-minor
    #   - dependency-name: "boto3-stubs"
    #     update-types:
    #       - version-update:semver-patch
    #       - version-update:semver-minor
    #   - dependency-name: "botocore"
    #     update-types:
    #       - version-update:semver-patch
    #       - version-update:semver-minor
    #   - dependency-name: "botocore-stubs"
    #     update-types:
    #       - version-update:semver-patch
    #       - version-update:semver-minor
    #   - dependency-name: "constructs"
    #     update-types:
    #       - version-update:semver-patch
    #       - version-update:semver-minor
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "pip"
    directory: "/api/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directories:
      - "**/aws_infra/"
    groups:
      cdk-deps-version-updates:
        applies-to: version-updates
        patterns:
          - "aws-cdk"
          - "cdk"
      cdk-deps-security-updates:
        applies-to: security-updates
        patterns:
          - "aws-cdk"
          - "cdk"
    # Below version upgrades are ignored because auto-updates on every PR should handle them
    # (package.json uses wildcards for minor and patch version definitions)
    # Dependabot will still create PRs for security upgrades with any version.
    #Note: ignoring patch and minor version temporarily disabled to test grouping behaviour
    # ignore:
    #   - dependency-name: "aws-cdk"
    #     update-types:
    #       - version-update:semver-patch
    #       - version-update:semver-minor
    #   - dependency-name: "cdk"
    #     update-types:
    #       - version-update:semver-patch
    #       - version-update:semver-minor
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/pipeline/seq_retrieval/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/webui/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
