# For all configuration options, see the GitHub documentation:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# TODO: using "groups", "directories" and "ignore" directives:
#        * Group Python testing framework updates (mypy, flake8, ...) accross components? To be implemented and tested once such updates become available

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directories:
      - "**/aws_infra/"
      - "/shared_aws/py_package/"
    groups:
      cdk-deps-version-updates:
        applies-to: version-updates
        patterns:
          - "boto3"
          - "boto3-stubs"
          - "botocore"
          - "botocore-stubs"
          - "aws-cdk-*"
      cdk-deps-security-updates:
        applies-to: security-updates
        patterns:
          - "boto3"
          - "boto3-stubs"
          - "botocore"
          - "botocore-stubs"
          - "aws-cdk-*"
    ignore:
      # Subdependencies temporarily added to ignore list to deal with lack of subdependency support in requirements.txt files.
      # TODO: migrate to poetry 2.* once released as stable release (support for )
      #       Tracked by https://github.com/dependabot/dependabot-core/issues/8603 and https://github.com/python-poetry/poetry/issues/9136
      #       Then remove this sub-dependency ignore list
      - dependency-name: "typeguard"
      - dependency-name: "cattrs"
      - dependency-name: "s3transfer"
      - dependency-name: "types-s3transfer"
      - dependency-name: "aws-cdk-cloud-assembly-schema"
      - dependency-name: "constructs"
      # Below version upgrades are ignored because auto-updates on every PR should handle them
      # (pyproject.toml uses wildcards for minor and patch version definition)
      # Dependabot will still create PRs for security upgrades with any version.

      - dependency-name: "aws-cdk-*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "boto3"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "boto3-stubs"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "botocore"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "botocore-stubs"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  - package-ecosystem: "pip"
    directory: "/api/"
    groups:
      aws-deps-version-upgrades:
        applies-to: version-updates
        patterns:
          - "boto3"
          - "botocore"
      aws-deps-security-upgrades:
        applies-to: security-updates
        patterns:
          - "boto3"
          - "botocore"
    # Below version upgrades are ignored because auto-updates on every PR should handle them
    # (pyproject.toml uses wildcards for minor/patch version definitions)
    # Dependabot will still create PRs for security upgrades with any version.
    ignore:
      - dependency-name: "fastapi[standard]"
        update-types:
          - version-update:semver-patch
      - dependency-name: "smart-open[s3]"
        update-types:
          - version-update:semver-patch
      # Subdependencies temporarily added to ignore list to deal with lack of subdependency support in requirements.txt files.
      # TODO: migrate to poetry 2.* once released as stable release (support for PEP-621-defined pyproject.toml files)
      # TODO: continue expanding ignore lists for all components to remove all irrelevant version-update PRs
      - dependency-name: "httpcore"
      - dependency-name: "websockets"
      - dependency-name: "uvicorn[standard]"
      - dependency-name: "python-multipart"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directories:
      - "**/aws_infra/"
    groups:
      cdk-deps-version-updates:
        applies-to: version-updates
        patterns:
          - "aws-cdk"
          - "cdk"
      cdk-deps-security-updates:
        applies-to: security-updates
        patterns:
          - "aws-cdk"
          - "cdk"
    # Below version upgrades are ignored because auto-updates on every PR should handle them
    # (package.json uses wildcards for minor and patch version definitions)
    # Dependabot will still create PRs for security upgrades with any version.
    ignore:
      - dependency-name: "aws-cdk"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "cdk"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/pipeline/seq_retrieval/"
    schedule:
      interval: "monthly"
    # Below version upgrades are ignored because auto-updates on every PR should handle them
    # (pyproject.toml uses wildcards for minor/patch version definitions)
    # Dependabot will still create PRs for security upgrades with any version.
    ignore:
      - dependency-name: "click"
        update-types:
          - version-update:semver-patch
      - dependency-name: "pysam"
        update-types:
          - version-update:semver-patch
      - dependency-name: "requests"
        update-types:
          - version-update:semver-patch
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/webui/"
    groups:
      next-js-deps-version-upgrades:
        applies-to: version-updates
        patterns:
          - "next"
          - "@tsconfig/next"
          - "eslint-config-next"
      next-js-deps-security-upgrades:
        applies-to: security-updates
        patterns:
          - "next"
          - "@tsconfig/next"
          - "eslint-config-next"
      jest-deps-version-upgrades:
        applies-to: version-updates
        patterns:
          - "@jest/globals"
          - "jest"
          - "jest-environment-jsdom"
          - "@types/jest"
      jest-deps-security-upgrades:
        applies-to: security-updates
        patterns:
          - "@jest/globals"
          - "jest"
          - "jest-environment-jsdom"
          - "@types/jest"
      react-deps-version-upgrades:
        applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      node-deps-version-upgrades:
        applies-to: version-updates
        patterns:
          - "node"
          - "@types/node"
    # Below version upgrades are ignored because auto-updates on every PR should handle them
    # (package.json uses wildcards for minor and patch version definitions)
    # Dependabot will still create PRs for security upgrades with any version.
    ignore:
      - dependency-name: "primeflex"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "primeicons"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "primereact"
        update-types:
          - version-update:semver-patch
      - dependency-name: "react"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "react-dom"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "uuid"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "@types/react"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "@types/react-dom"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "node"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
