# For all configuration options, see the GitHub documentation:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/pipeline/seq_retrieval/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/pipeline/aws_infra/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/api/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/api/aws_infra/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/shared_aws_infra/"
    schedule:
      interval: "monthly"
