#!/usr/bin/env python3
"""
Main module serving the CLI for PAVI sequence info align component.

Collects and merges sequence info generated by the sequence retrieval component
 + adds relative alignment positions for all variants using alignment results.
"""

from Bio import AlignIO
from Bio.SeqRecord import SeqRecord
from Bio.Align import MultipleSeqAlignment
from copy import deepcopy
import click
from enum import Enum
import glob
import json
import jsonpickle  # type: ignore
import logging
import os
import subprocess
from typing import Any, List, Optional

from log_mgmt import set_log_level, get_logger
from variant import AlignmentEmbeddedVariant, AlignmentEmbeddedVariantsList
from seq_info import EnumValueHandler, SeqInfo

logger = get_logger(name=__name__)


def download_from_s3(s3_prefix: str, local_dir: str, pattern: str = "*") -> List[str]:
    """
    Download files from S3 to local directory.

    Args:
        s3_prefix: S3 URI prefix (e.g., s3://bucket/prefix/)
        local_dir: Local directory to download to
        pattern: File pattern to include (default: all files)

    Returns:
        List of downloaded local file paths
    """
    os.makedirs(local_dir, exist_ok=True)

    logger.info(f"Downloading files from {s3_prefix} to {local_dir}...")

    result = subprocess.run(
        ["aws", "s3", "cp", s3_prefix, local_dir, "--recursive", "--include", pattern],
        capture_output=True,
        text=True,
    )
