import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";

import { PrimeReactProvider } from 'primereact/api';

import { DarkModeToggle } from './components/DarkModeToggle';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "PAVI webUI pilot",
    description: "Generated by create next app",
    icons: "https://www.alliancegenome.org/favicon-16x16.png",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <PrimeReactProvider>
                {/* eslint-disable-next-line @next/next/no-css-tags */}
                <link id="theme-link" rel="stylesheet" href="/themes/mdc-light-indigo/theme.css" />
                <DarkModeToggle />
                <br />
                {children}
            </PrimeReactProvider>
        </body>
        </html>
    );
}
