[project]
name = "shared_aws_infra"
version = "0.1.0"
description = "PAVI shared AWS resource definitions"
authors = [
    {name = "Manuel Luypaert", email = "luypaert@ebi.ac.uk"}
]

requires-python = "==3.12.*"
dependencies = [
    "aws-cdk-lib==2.141.*",
    "constructs==10.*"
]
