ARG NODE_VERSION
FROM node:${NODE_VERSION:-20}-bookworm AS base

RUN apt update && apt upgrade -y

# Install dependencies only when needed
FROM base AS deps
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json package-lock.json ./
RUN npm ci

# Production image, copy all the files and run cypress tests
FROM base AS testrunner

ARG PAVI_API_BASE_URL

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
RUN npx cypress install && npx cypress verify

EXPOSE 3000

# Run cypress tests
# CMD ["npx", "cypress", "run", "--e2e", "--env", "API_BASE_URL=${PAVI_API_BASE_URL}"]
