# Local dev env symlinks
src/nextflow.sh
src/nextflow.config
src/*.nf
# Nextflow output files
src/seq_regions*.json
src/.nextflow*
src/pipeline-results*/
src/work/
# AWS infra code and config files
aws_infra/
