name: PR validation
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]
    branches:
      - main
jobs:
  pipeline-seq-retrieval-container-image-build:
    name: pipeline/seq_retrieval container-image build
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./pipeline/seq_retrieval/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout: |
            pipeline/seq_retrieval/
      - name: Build container image
        run: |
          make container-image
  #TODO: add typing testing (mypy)
  #TODO: add unit testing
  #TODO: add integration testing
