name: PR validation
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]
    branches:
      - main
jobs:
  pipeline-seq-retrieval-container-image-build:
    name: pipeline/seq_retrieval container-image build
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./pipeline/seq_retrieval/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout: |
            pipeline/seq_retrieval/
      - name: Build container image
        run: |
          make container-image
  pipeline-seq-retrieval-check-python-typing:
    name: pipeline/seq_retrieval check python typing
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./pipeline/seq_retrieval/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout: |
            pipeline/seq_retrieval/
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Check python typing
        run: |
          make check-python-typing
  #TODO: add unit testing
  #TODO: add integration testing
